version: '3'

services:
    backend:
        container_name: backend
        build:
            context: ./
            dockerfile: Dockerfile
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - 8080:8080
        depends_on:
            - postgresqldb
    postgresqldb:
        container_name: pg
        image: postgres:15-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_NAME}
